version: 2.1

jobs:
  code-check:
    docker:
      - image: "python:3.12"
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: python -m pip install -U nox pip uv
          no_output_timeout: 5m
      - run:
          name: Run ruff
          command: nox -s code-check

  test:
    resource_class: large
    parameters:
      python:
        type: string
        default: "3.12"
    docker:
      - image: "python:<< parameters.python >>"
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            pip install nox
      - run:
          name: Run tests
          command: |
            nox -s tests-<< parameters.python >>
          no_output_timeout: 10m

workflows:
  main:
    jobs:
      - code-check
      - test
